capture = kms
encoder = nvenc
output_name = 0

nvenc_preset = 4
nvenc_twopass = full_res
nvenc_spatial_aq = enabled

global_prep_cmd = [{"do":"hyprctl keyword animations:enabled false && hyprctl keyword misc:vfr false","undo":"hyprctl keyword animations:enabled true && hyprctl keyword misc:vfr true"},{"do":"hyprctl dispatch workspace 5","undo":"hyprctl dispatch workspace 1"}]
