# Workspace names (shown in Noctalia bar)
workspace = 1, name:󰆍 terminal
workspace = 2, name:󰖟 browser
workspace = 3, name:󰨞 code
workspace = 4, name:󰭹 chat
workspace = 5, name:󰊗 games
workspace = 6, name:󰀻 misc
workspace = 7, name:󰀻 misc
workspace = 8, name:󰀻 misc
workspace = 9, name:󰀻 misc
workspace = 10, name:󰀻 misc

# Source all config files
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/noctalia/noctalia-colors.conf
