general {
  lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 600                          # 10 minutes - lock screen
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 900                          # 15 minutes: shutdown if 1am-7am (after lock)
    on-timeout = bash -c 'h=$(date +%H); [ "$h" -ge 1 ] && [ "$h" -lt 7 ] && systemctl poweroff'
}

listener {
    timeout = 1800                         # 30 minutes - screen off
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 7200                         # 2 hours - shutdown
    on-timeout = systemctl poweroff
}
